server:
  port: 8080

spring:
  # 数据库 —— 100% 正确
  datasource:
    url: jdbc:mysql://inline.proxy.rlwy.net:56928/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: SHiWjqZYIVQpQTicwhouYPEKAICQUJ
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.shiyizi.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 关闭文件上传检查
servlet:
  multipart:
    enabled: false
