spring:
  # 数据库 —— 100% 正确
  datasource:
    url: jdbc:mysql://inline.proxy.rlwy.net:56928/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: SHiWjqZYIVQpQTicwhouYPEKAICQUJ
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  cloud:
    alicloud:
      oss:
        endpoint: https://oss-cn-guangzhou.aliyuncs.com
        bucket-name: home-pageimage
        region: cn-guangzhou
mybatis:
  type-aliases-package: org.shiyizi.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
