spring:
  datasource:
    url: jdbc:mysql://localhost:3306/our_websql
    username: root
    password: syz20060705
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

server:
  port: 8080
